export const REFERRAL_CODE = 'REFERRAL_CODE';
export const REFERRAL_CODE_POST = 'REFERRAL_CODE_POST';
export const GENERATE_CODE = 'GENERATE_CODE';
export const GET_REFERRALS = 'GET_REFERRALS';
export const POST_REFERRALS = 'POST_REFERRALS';
export const DELETE_REFERRALS = 'DELETE_REFERRALS';
export const LAST_REFERRAL_CODE = 'LAST_REFERRAL_CODE';
